<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>With Love <a href="https://www.osia.cz" target="_blank">OSIA</a>, <?= date("Y") ?></p>
        </div>
    </div>
</footer>

</div>
<?php
$url = \core\core::urlToAssets();
$baseurl = "web/";
foreach ($url as $item){
    $baseurl .= "../";
}
?>
<!-- jQuery -->
<script src="<?= $baseurl ?>assets/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?= $baseurl ?>assets/js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
</script>

</body>

</html>