<?php
$url = \core\core::urlToAssets();
$baseurl = "web/";
    var_dump($url);
foreach ($url as $item){
    $baseurl .= "../";
}
?>
<!doctype html>
<html lang="cs" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="http://html5-templates.com/" />
    <title><?= $title ?></title>
    <meta name="description" content="A minimalist Bootstrap theme by StartBootstrap. Contains everything you need to get started building your website. All you have to do is change the text and images.">
    <link href="<?= $baseurl ?>assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= $baseurl ?>assets/css/modern-business.css" rel="stylesheet">
    <link href="<?= $baseurl ?>assets/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>