-- MySQL Script generated by MySQL Workbench
-- Tue Mar 20 22:27:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema brnofe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `brnofe` ;

-- -----------------------------------------------------
-- Schema brnofe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brnofe` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `brnofe` ;

-- -----------------------------------------------------
-- Table `brnofe`.`siteinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`siteinfo` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`siteinfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brnofe`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`user` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`user` (
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `brnofe`.`login_attempt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`login_attempt` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`login_attempt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `brnofe`.`foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`foto` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `path` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brnofe`.`galerie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`galerie` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`galerie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galerie_foto1_idx` (`foto_id` ASC),
  CONSTRAINT `fk_galerie_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `brnofe`.`foto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brnofe`.`kavarna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`kavarna` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`kavarna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(255) NULL,
  `hodnoceni` VARCHAR(45) NULL,
  `popis` TEXT NULL,
  `adresa` TEXT NULL,
  `galerie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kavarna_galerie1_idx` (`galerie_id` ASC),
  CONSTRAINT `fk_kavarna_galerie1`
    FOREIGN KEY (`galerie_id`)
    REFERENCES `brnofe`.`galerie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brnofe`.`kavy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`kavy` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`kavy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `popis` TEXT NULL,
  `galerie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_kavy_galerie1_idx` (`galerie_id` ASC),
  CONSTRAINT `fk_kavy_galerie1`
    FOREIGN KEY (`galerie_id`)
    REFERENCES `brnofe`.`galerie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brnofe`.`kavy_has_kavarna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brnofe`.`kavy_has_kavarna` ;

CREATE TABLE IF NOT EXISTS `brnofe`.`kavy_has_kavarna` (
  `kavy_id` INT NOT NULL,
  `kavarna_id` INT NOT NULL,
  `hodnoceni` VARCHAR(45) NULL,
  `popis` TEXT NULL,
  PRIMARY KEY (`kavy_id`, `kavarna_id`),
  INDEX `fk_kavy_has_kavarna_kavarna1_idx` (`kavarna_id` ASC),
  INDEX `fk_kavy_has_kavarna_kavy1_idx` (`kavy_id` ASC),
  CONSTRAINT `fk_kavy_has_kavarna_kavy1`
    FOREIGN KEY (`kavy_id`)
    REFERENCES `brnofe`.`kavy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_kavy_has_kavarna_kavarna1`
    FOREIGN KEY (`kavarna_id`)
    REFERENCES `brnofe`.`kavarna` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
