<!-- Navigation -->
<?php
$url = \core\core::urlToAssets();
$baseurl = "web/";
foreach ($url as $item){
    $baseurl .= "../";
}
?>

<body>
<div id="wrapper">
    <!-- h1 tag stays for the logo, you can use the a tag for linking the index page -->
    <h1><span>Bel3s</span></h1>

    <!-- You can name the links with lowercase, they will be transformed to uppercase by CSS, we prefered to name them with uppercase to have the same effect with disabled stylesheet -->
    <ul id="mainNav">
        <li><a href="#" 	>Jídlo				</a></li> <!-- Use the "active" class for the active menu item  -->
        <li><a href="#" 	>Objednavky			</a></li>
        <li><a href="#" 	>Uživatelé			</a></li>
        <li><a href="#" 	>Nastavení			</a></li>
        <li class="logout"><a href="#">Odhlásit se</a></li>
    </ul>
    <!-- // #end mainNav -->