<?php
$url = \core\core::urlToAssets();
$mode = \core\core::$configFile['mode']();
if ($mode == 'dev' OR $mode == 'test') {
    $baseurl = "web/";
} else {
    $baseurl = "/";
}
foreach ($url as $item){
    $baseurl .= "../";
}
?>
<!doctype html>
<html lang="cs" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Administrace</title>

    <!-- CSS -->
    <link href="<?= $baseurl ?>assets/css/transdmin.css" rel="stylesheet" type="text/css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie6.css" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" media="screen" href="style/css/ie7.css" /><![endif]-->
    <!-- Compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Latest compiled and minified CSS -->

    <!-- JavaScripts-->
    <script type="text/javascript" src="<?= $baseurl ?>assets/js/jquery_admin.js"></script>
    <script type="text/javascript" src="<?= $baseurl ?>assets/js/jNice.js"></script>
</head>